### ISSUE TITLE
Fix pylint in some ported modules

### ISSUE THREAD

**Issue by OctoNezd** [OctoNezd/Octeon#1]
Pylint screams at them

**Comment by OctoNezd** [comment]
![image](https://cloud.githubusercontent.com/assets/15308404/24581284/37ec0952-1721-11e7-952f-247b62fd71e6.png)

**Comment by kovirolik** [comment]
Can it screams without mouth? No. Also , PyLint ironically have no mouth.

**Comment by OctoNezd** [comment]
It is magic
