### ISSUE TITLE
Copyright

### ISSUE THREAD

**Issue by mrsteyk** [OctoNezd/Octeon#4]
У `RobotoMono` лицензия `Apache 2.0`. По условиям лицензии должен быть файл `LICENSE` с содержанием лицензии `Apache 2.0` и файл `NOTICE` с содержанием перечисления всех работ, лицензированных под лицензией `Apache` вместе с именами их создателей.

**Comment by mostm** [comment]
@mrsteyk А тебе не насрать?

**Comment by mrsteyk** [comment]
@mrsteyk лойль в телеге нет форматирования

**Comment by OctoNezd** [comment]
@mrsteyk Блять ебаный врот

**Comment by mrsteyk** [comment]
@OctoNezd не ленись падла

**Comment by OctoNezd** [comment]
нет делай ты

**Comment by OctoNezd** [comment]
Убрал Roboto https://github.com/OctoNezd/Octeon/commit/7d2bc5cb2f835e08622038f8d6c62a5f47932968
